### ISSUE TITLE
[CRJVM204] [Java] Detect unoptimized file formats

### ISSUE THREAD

**Issue by nouk-pl** [green-code-initiative/ecoCode#105]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nouk-pl** [comment]
Team 1.5 implements this rule

**Comment by dedece35** [comment]
Hi @nouk-pl 
please delete first useless comment.

thx

**Comment by dedece35** [comment]
please check discussion inside PR #153
