### ISSUE TITLE
[EC67] [Python] Use the $i++ variable during an iteration

### ISSUE THREAD

**Issue by julessanglier** [green-code-initiative/ecoCode#106]
[ecoCode challenge 2023 - Team 28 days]

**Is your feature request related to a problem? Please describe.**
The i++ form has the disadvantage of generating a temporary variable during incrementation, which is not the case with the ++i form.

**Comment by julessanglier** [comment]
Pas d'opérateur post fixé en Python ... (idem pour Rust à priori)
Merci de basculer la tâche en JS

**Comment by jycr** [comment]
More information here:
* [Python Increment Operation - AskPython](https://www.askpython.com/python/examples/python-increment-operation)
* [Python Documentation on Assignment Statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements)

**Comment by dedece35** [comment]
please update RULES.md with a X for python an Rust

**Comment by dedece35** [comment]
done with commit https://github.com/green-code-initiative/ecoCode/commit/c2e2cbe8910691aa1fcf02e788385a2b5e4a7c0e
