### ISSUE TITLE
[EC66] [Python] Use single quote (') instead of quotation mark (")

### ISSUE THREAD

**Issue by JB-Ginguene** [green-code-initiative/ecoCode#108]
[ecoCode challenge 2023 - Team 28 days]

The shape using the quotation marks allows the developer to insert variables that will be substituted at run time. But if the string does not have a variable, use quotes instead. Thus, language will not look for variables to subtituture, which will reduce the consumption of CPU cycles.

**Comment by dedece35** [comment]
closed because of PR merged and available on 1.3.0 release
