### ISSUE TITLE
EC34 [PHP]  : rework rule

### ISSUE THREAD

**Issue by Silicoman** [green-code-initiative/ecoCode#115]
**Describe the bug**
Identification d'une regle dont le code source n'est pas fonctionnel.

Class : AvoidTryCatchFinallyCheck_NOK_failsAllTryStatements

En cours de refonte par l'**equipe 5R**

**Comment by dedece35** [comment]
other issue on the same subject : https://github.com/green-code-initiative/ecoCode/issues/173

**Comment by dedece35** [comment]
issue closed because of migration on new PHP repository https://github.com/green-code-initiative/ecoCode-php/issues/8
