### ISSUE TITLE
[EC7] [Java] [Python] Getter/Setters not to do by overload + update Python ressource file

### ISSUE THREAD

**Issue by Houssainatou** [green-code-initiative/ecoCode#123]
**Equipe 5R**

**Comment by Houssainatou** [comment]
Cette règle n'est pas valable en java car supprimer les getters/setters impliquerait de changer la visibilité des attributs, ce qui ne respecte pas le principe.

**Comment by Silicoman** [comment]
@Houssainatou  , tu peux rename le titre avec le titre + python pour que personne reimplemente les corrections ?

**Comment by Silicoman** [comment]
PR  #134

**Comment by dedece35** [comment]
la remarque est aussi valable en PHP : si attribut privé alors si présence d'un getter et/ou un setter il NE faut PAS remonter d'alertes (car c'est une bonne pratique = validé avec un archi PHP de chez PagesJaunes)

autre idée à implémenter : si un attribut est public (ça peut arriver en PHP par xemple dans certains cas) et qu'il existe un getter et/ou un setter alors remonter une alerte car ne servent à rien

**Comment by dedece35** [comment]
@jhertout @utarwyn @glalloue 
on est ok du coup qu'on marque la règle EC7 comme non applicable en Java ni en PHP ?
(pour python, c'est ok)

**Comment by dedece35** [comment]
issue closed because modifications done on differents repositories (now, we have one repository by language for ecocode).
all is ok.
thank you a lot @Silicoman @Houssainatou
