### ISSUE TITLE
EC69[JS] - Calling a function in the declaration of a for loop

### ISSUE THREAD

**Issue by julessanglier** [green-code-initiative/ecoCode#130]
[ecoCode Challenge 2023 - Team 28 days]

Is your feature request related to a problem? Please describe.
Calling a function in the declaration of a for loop

**Comment by utarwyn** [comment]
Hello! Did you have time to work on this rule during the challenge? I have not found the associated PR.

Maybe we need to talk about the relevance of the rule? I'm afraid that the gain is very small (even questionable) and that the number of false positives is very high: function calls in loops are quite frequent. Do you know a scientific paper or documentation on the subject?

**Comment by utarwyn** [comment]
Feel free to re-open an issue in [ecoCode-javascript repository](https://github.com/green-code-initiative/ecoCode-javascript) to continue the discussion :+1:
