### ISSUE TITLE
[EC53] [Python] to disable for Python ?

### ISSUE THREAD

**Issue by Ella-dee** [green-code-initiative/ecoCode#136]
La règle "EC53 | Using arrays in foreach loops" est notée "à faire" pour le langage python, mais la boucle "foreach" n'existe pas en python. 
La boucle "for" classique en python reproduit déjà le comportement d'une "foreach", mais on ne peut pas pour ce langage utiliser "une simple boucle for" pour les arrays, vu qu'il n'y a qu'un seul type de boucle for.

**Comment by dedece35** [comment]
done with https://github.com/green-code-initiative/ecoCode/commit/67e93e7b2f817d687b0011666caac4f70904fb85
