### ISSUE TITLE
[EC3] [Python] To disable for python ?

### ISSUE THREAD

**Issue by Ella-dee** [green-code-initiative/ecoCode#140]
La règle EC3 "Getting the size of the collection in the loop" est notée "à faire" dans python, mais les boucles for en python sont sur le principe d'une boucle foreach, on ne prend donc pas la taille du tableau:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    break
  print(x)

**Comment by dedece35** [comment]
done with https://github.com/green-code-initiative/ecoCode/commit/1bd5870b5fe3911261650982c5315ec305377b11
