### ISSUE TITLE
[DOC] Indicate how to fast relaunch Sonar when developping

### ISSUE THREAD

**Issue by MP-Aubay** [green-code-initiative/ecoCode#149]
**Is your feature request related to a problem? Please describe.**
When developping new rule it is a bit annoying to do all configurations (Profiles, admin password, token, ...) all over again.
Happen when using : 
```sh
./tool_docker-clean.sh (= docker-compose down --volumes )
./tool_build.sh (= mvn clean package -DskipTests)
./tool_docker-init.hs (= docker-compose up --build -d)
```

**Describe the solution you'd like**
We need to only restart container with new plugin jar and eventually adding the new rule in profile.

**Comment by dedece35** [comment]
Hi @MP-Aubay,

there is a documentation about it but maybe we can complete a little more, isn't it ? 
https://github.com/green-code-initiative/ecoCode-common/blob/main/doc/INSTALL.md#howto-start-or-stop-service-already-installed

for example, improve the doc to explain that we can only restart SonarQube, after built the plugin, to reload plugins in local SonarQube.

**Comment by MP-Aubay** [comment]
Hi @dedece35 ,

Shame on me, I had not see that !

I close the Issue.
