### ISSUE TITLE
EC63 - issue message still doesn’t make sense

### ISSUE THREAD

**Issue by jycr** [green-code-initiative/ecoCode#166]
When analyze https://github.com/green-code-initiative/ecoCode-java-test-project.git, following is raised:

> The variable is not assigned

for following code:

```java
        final int len = 5;
```

![image](https://user-images.githubusercontent.com/51145/231148611-3ded9e5c-1e91-43eb-a111-65856870e2e6.png)

Explicitly, the variable is assigned.

**Comment by jycr** [comment]
According to the corresponding test case ([java-plugin/src/test/files/UnnecessarilyAssignValuesToVariablesTestCheck.java](https://github.com/green-code-initiative/ecoCode/blob/1.1.0/java-plugin/src/test/files/UnnecessarilyAssignValuesToVariablesTestCheck.java)), shouldn't the message instead be:

> The variable is never read

Or

> The variable is never used

?

**Comment by dedece35** [comment]
Hi @jycr 
PR done : #172 

indeed, only a message problem.
