### ISSUE TITLE
Split repository

### ISSUE THREAD

**Issue by jycr** [green-code-initiative/ecoCode#182]
As discussed on Slack, repositories should be split based on languages and/or platform.
This is so that each plugin can have its own development cycle.

For the "code" part, I found several methods:

- [GitHub Docs - Splitting a subfolder out into a new repository](https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository)
- [How to split a git repository into two different ones](https://gist.github.com/mvneves/23878af4789f6a5ab05079feb8097550)
- [Splitting Your Git Repo While Maintaining Commit History](https://amandawalkerbrubaker.medium.com/splitting-your-git-repo-while-maintaining-commit-history-35b9f4597514)
- [Git — How to Split Git SubDirectory into Separate Repository?](https://schhajed.medium.com/git-how-to-split-subdirectory-to-separate-repository-ab0dcff6a82a)
- [Difference between git filter-branch subdirectory-filter & git subtree split -P](https://stackoverflow.com/questions/61127751/difference-between-git-filter-branch-subdirectory-filter-git-subtree-split-p#answer-61150846)

To migrate issues, I found this:
- [GitHub Docs - Transferring an issue to another repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository)

**Comment by dedece35** [comment]
To complete this issue, only to do once all (or most) actives PRs merged (no to report opened PRs)

**Comment by dedece35** [comment]
Status : 
- PHP OK : https://github.com/green-code-initiative/ecoCode-php
- Python OK : https://github.com/green-code-initiative/ecoCode-python
- Java IN PROGRESS : cleaning / working on Java issues
