### ISSUE TITLE
Use "Maven Friendly Version"

### ISSUE THREAD

**Issue by jycr** [green-code-initiative/ecoCode#208]
By using the "[Maven Friendly Version](https://maven.apache.org/maven-ci-friendly.html)" guide, there is no more `pom.xml` file modification needed in Git for a release.

And next, do the same on other languages plugins

**Comment by dedece35** [comment]
Hi @jycr,
thank you for this issue, I think it's a real good idea to explore. I didn't know this maven feature.
I really would want to explore it, if you are ok.
