### ISSUE TITLE
I can't apply the ecoCode Sonar plugin rules (release 0.1.0) to Java Project

### ISSUE THREAD

**Issue by fabioquimbay** [green-code-initiative/ecoCode#21]
**Describe the bug**
I can't force to obtain this code smell: **Avoid multiple if-else statement** for a Java project.

**To Reproduce**
1. I downloaded the release 0.1.0 of ecoCode Sonar Plugin.
2. I followed all steps described in the documentation, in **INSTALL.md** file.
3. I created a Java project with a bad practice, as follow:

![bad_practice](https://user-images.githubusercontent.com/1473124/208451624-9d344c27-0c75-4ee5-a8de-a41f3acf7c2e.png)

4. After create the SonarQube token, I analyze my Java project with these lines:

`./gradlew sonarqube -Dsonar.projectKey=KC-Spring-Native 
     -Dsonar.host.url=http://localhost:9000/ 
     -Dsonar.login=<token_generated>`

5. From the Logs perspective (Java App & Docker image) I didn't see any exception or error, seems the Analysis were performed successfully.

`sonar_standard       | 2022.12.16 23:57:39 INFO  ce[][o.s.c.t.CeWorkerImpl] Execute task | project=KC-Spring-Native | type=REPORT | id=AYUdXzh92hVIDeT3_WTc | submitter=admin
sonar_standard       | 2022.12.16 23:57:41 INFO  ce[AYUdXzh92hVIDeT3_WTc][o.s.c.t.s.ComputationStepExecutor] Extract report | status=SUCCESS | time=178ms
...
sonar_standard       | 2022.12.16 23:57:59 INFO  ce[AYUdXzh92hVIDeT3_WTc][o.s.c.t.p.a.p.PostProjectAnalysisTasksExecutor] Webhooks | globalWebhooks=0 | projectWebhooks=0 | status=SUCCESS | time=42ms
sonar_standard       | 2022.12.16 23:58:00 INFO  ce[AYUdXzh92hVIDeT3_WTc][o.s.c.t.CeWorkerImpl] Executed task | project=KC-Spring-Native | type=REPORT | id=AYUdXzh92hVIDeT3_WTc | submitter=admin | status=SUCCESS | time=20734ms
`

6. However, I obtained these code smells using the default Java Profile (Sonar way), but not any ecoCode rule were applied: 

![rules_applied](https://user-images.githubusercontent.com/1473124/208452855-b5d952b8-caad-43ad-a575-7fb61bd9207e.png)

7. Also I modified the file: tool_start.sh with these line (in order to be aligned with the generated token):

`TOKEN=<token_generated> docker-compose start`

**Expected behavior**
I expected to see an output similar to these one (but oriented to the **Avoid multiple if-else statement**), as follow:

![expected_result](https://user-images.githubusercontent.com/1473124/208453694-b7fe9475-fa78-4430-8d54-174605a04a7b.png)

**Screenshots**
See previous ones.

**Software Versions**
 - MacOS Monterrey M1 12.3
 - Docker Desktop 4.15.0
 - SonarQube image: sonarqube:9.7-community (directly modified from _docker-compose.yml_)
 - Plugin Version: [0.1.0](https://github.com/green-code-initiative/ecoCode/releases/tag/v0.1.0) - 2022-12-14

**Additional context**
 - For both services: sonar and db (in docker-compose.yml) I had to add this line:
 `platform: linux/amd64`
 - Since I'm not using PHP nor Python, I commented these lines (in docker-compose.yml), as follow:
 `type: bind
   source: ./php-plugin/target/ecocode-php-plugin-0.1.0-SNAPSHOT.jar
   target: /opt/sonarqube/extensions/plugins/ecocode-php-plugin-0.1.0-SNAPSHOT.jar
   type: bind
   source: ./python-plugin/target/ecocode-python-plugin-0.1.0-SNAPSHOT.jar
   target: /opt/sonarqube/extensions/plugins/ecocode-python-plugin-0.1.0-SNAPSHOT.jar`

Thanks in advance for your support!

**Comment by Silicoman** [comment]
Hi @fabioquimbay 
At the moment, you have to create a new Profile with sonar way as parent profile. You can call it "ecocode sonar". You have to add the new rules to this profile. You can find rules by the tag "eco-conception".
The default profile "sonar way" is provided by sonarsource. It was previously discussed with them to not modify this one.

Create a profile with script it's a new feature. Be reassured, It's already identified! :)

**Comment by dedece35** [comment]
hi @Silicoman 
i'm agree with ... it's a profile configuration problem.
do you have an issue to follow with this new functionnality ? i don't hear about this subject yet.

**Comment by fabioquimbay** [comment]
Thank you so much @Silicoman and @dedece35, I followed the steps described previously, and now I can see the eco-conception tags after analyze my custom project, as follow: 

![ecoCode-qualityProfile](https://user-images.githubusercontent.com/1473124/208973126-9b4d8e9d-5b0b-418e-8f6e-05c17e9c8333.png)

I'll be attentive to any future release and improvement. Thanks again!

**Comment by dedece35** [comment]
@fabioquimbay 
OK. I close this issue. 

thank you.
