### ISSUE TITLE
[EC63] UnnecessarilyAssignValuesToVariables rule on caught exception

### ISSUE THREAD

**Issue by natixis-caen** [green-code-initiative/ecoCode#228]
**Describe the bug**
Caught exceptions but not used are analyzed as code smells.

**To Reproduce**
1. Add this code snippet in file [UnnecessarilyAssignValuesToVariablesTestCheck.java](https://github.com/green-code-initiative/ecoCode/blob/main/java-plugin/src/test/files/UnnecessarilyAssignValuesToVariablesTestCheck.java)
```java
public void testCompliantCatchException() throws Exception {
    try {
        int i = 1;
        System.out.println(i);
    } catch (Exception e) { // Noncompliant {{The variable is declared but not really used}}
        System.out.println("Something went wrong.");
    }
}
```
2. Run unit test
3. The code is non compliant

**Expected behavior**
The caught exception should be allowed to be unused.

**Software Versions**
 - SonarQube Version: Version 9.9.1 (build 69595)
 - Plugin Version: 1.4.0

**Comment by dedece35** [comment]
Hi @natixis-caen,
thank you for issue.
I agree with for Java language.

Do you think you can make this correction in a new PR ? if yes, I can be the reviewer if you want.

thank you.

**Comment by natixis-caen** [comment]
Hi @dedece35 ,
I can try to fix it, I guess I have to find a way to exclude exception variables in this method:
```java
    private class GetVariableVisitor extends BaseTreeVisitor {
        @Override
        public void visitVariable(VariableTree tree) {
            if (!tree.parent().is(Kind.METHOD)) {
                variableList.put(tree.simpleName().name(), tree);
            }
            super.visitVariable(tree);
        }
    }
```

Any help would be appreciated!

**Comment by natixis-caen** [comment]
Here is the PR:
https://github.com/green-code-initiative/ecoCode/pull/230

**Comment by dedece35** [comment]
Thank you ... do you check de DoD list when a developer contribute ?
please check it and then tell me when ok for review : https://github.com/green-code-initiative/ecoCode-common/blob/main/doc/starter-pack.md#definition-of-done-of-a-pr

**Comment by dedece35** [comment]
Hi @natixis-caen,
sorry but regarding [DoD list](https://github.com/green-code-initiative/ecoCode-common/blob/main/doc/starter-pack.md#definition-of-done-of-a-pr) , you didn't create a PR in test-project to update it with the new use case
(here is real test-project for java language : https://github.com/green-code-initiative/ecoCode-java-test-project/blob/main/src/main/java/fr/greencodeinitiative/java/checks/UnnecessarilyAssignValuesToVariablesTestCheck.java)

**Comment by natixis-caen** [comment]
Hello,
I did add a compliant test actually:
https://github.com/green-code-initiative/ecoCode/pull/230/files#diff-0f7d43ab11da0fdb865fdbd6c9f5631f4974452d5541afcd2ba34ea3de97cbe5

Did you missed it or am I totally wrong?

**Comment by natixis-caen** [comment]
Here it is: https://github.com/green-code-initiative/ecoCode-java-test-project/pull/11

**Comment by dedece35** [comment]
Please, wait for draft https://github.com/green-code-initiative/ecoCode/pull/258

**Comment by dedece35** [comment]
Hi @natixis-caen,
like said in related PR #230, the EC63 rule has been deprecated ... check details in PR #230
