### ISSUE TITLE
Test support with SonarQube 10.2 and 10.3

### ISSUE THREAD

**Issue by utarwyn** [green-code-initiative/ecoCode#241]
SonarQube 10.3 is out!
Here is the annoucement: https://www.sonarsource.com/blog/sonarqube-10-3-release-announcement/

Maybe we should try plugins on these two new versions and update the matrix in the README?

We may also work with the new clean code attributes to improve the referencing of our rules in the interface. [More info here](https://docs.sonarsource.com/sonarqube/10.3/user-guide/clean-code/)

**Comment by utarwyn** [comment]
Here is an example of a usage of the new clean code taxonomy: https://github.com/green-code-initiative/ecoCode/commit/e52fd183de115997da7bbe2d7b320e88c4f8f0dc
Note that we need to update **sonar-analyzer-commons** to **2.7.0** to have this feature working properly.

**Comment by dedece35** [comment]
> Here is an example of a usage of the new clean code taxonomy: [e52fd18](https://github.com/green-code-initiative/ecoCode/commit/e52fd183de115997da7bbe2d7b320e88c4f8f0dc) Note that we need to update **sonar-analyzer-commons** to **2.7.0** to have this feature working properly.

ok, but what are impacts of new taxonomy on older sonarqube version ? 9.8 for example.

**Comment by utarwyn** [comment]
> @dedece35 
> ok, but what are impacts of new taxonomy on older sonarqube version ? 9.8 for example.

The new taxononmy is ignored on older versions of SonarQube, that's why we need to continue to put deprecated values like "defaultSeverity" in metadata files. You can read more about the subjet on the [official SonarQube documentation](https://docs.sonarsource.com/sonarqube/10.2/user-guide/rules/overview/#how-rules-are-categorized).

**Comment by gabriel-vivas-sonarsource** [comment]
Hi, I would be happy to help out with this. Let me know if you want to have a first chat about it.

**Comment by dedece35** [comment]
During submition of 1.4.2 version, I must check compatibility to check the real versions to put on SonarQube PR.
I tested locally in docker each SonarQube version followed and for each plugin version followed.
Each time I launched the real test project of each language

| SonarQube version | plugin version | Java | PHP | Python |
| ------------------- | -------------- | ----- | ---- | ------- |
| 9.9.1                          | 1.2.1                 | OK    | OK   | OK        |
| 10.0                           | 1.2.1                 | OK    | OK   | OK        |
| 10.1                           | 1.2.1                 | OK    | OK   | OK        |
| 10.2                           | 1.2.1                 | OK    | OK   | OK        |
| 10.3                           | 1.2.1                 | OK    | OK   | OK        |
| 9.9.1                          | 1.3.0                 | OK    | OK   | OK        |
| 10.0                           | 1.3.0                 | OK    | OK   | OK        |
| 10.1                           | 1.3.0                 | OK    | OK   | OK        |
| 10.2                           | 1.3.0                 | OK    | OK   | OK        |
| 10.3                           | 1.3.0                 | OK    | OK   | OK        |
| 9.9.1                          | 1.4.2                 | OK    |         |              |
| 10.0                           | 1.4.2                 | OK    |         |              |
| 10.1                           | 1.4.2                 | OK    |         |              |
| 10.2                           | 1.4.2                 | OK    |         |              |
| 10.3                           | 1.4.2                 | OK    |         |              |

This is only verifications without code modification.
@utarwyn I agree with you that we should upgrade our internal libraries and upgrade README.md files

What do you think about it ?

**Comment by utarwyn** [comment]
@dedece35 Awesome work! Yes, so we can update the README file with support for SonarQube 9.9.+ LTS to 10.3

But what about version 9.4 (the minimum supported version according to the README)? I admit that I no longer test on this discontinued version. So maybe we can think of officially dropping support for this version, by upgrading the version in the pom file? (to discuss with the core team)

**Comment by dedece35** [comment]
hi @utarwyn 
for me, before updating `README.md`, I think we have to upgrade our code to reference last 10.3 version.
considering 9.4 version, I think we have to discuss about it during friday meeting ... I will talk about it tomorrow.

**Comment by dedece35** [comment]
I close this issue because code was updated and tested to check 10.3 compatibility.
