### ISSUE TITLE
[EC63] Evolution rule "The variable is declared but not really used"

### ISSUE THREAD

**Issue by epitechBR** [green-code-initiative/ecoCode#245]
![Capture d’écran du 2023-11-23 15-08-33](https://github.com/green-code-initiative/ecoCode/assets/113339802/9534af89-8ab7-43d8-ab60-41c52f199dce)

Gérer le fait qu'une variable soit appeler uniquement pour en remplir une autre sans être utilisé dans des appels fonction/méthode

**Comment by dedece35** [comment]
Please, wait for draft https://github.com/green-code-initiative/ecoCode/pull/258

**Comment by dedece35** [comment]
Hi @epitechBR 
as https://github.com/green-code-initiative/ecoCode/pull/258 has been merged to deprecate rule EC63, this issue is directly closed.
