### ISSUE TITLE
[EC75] Useless rule - deprecation

### ISSUE THREAD

**Issue by csauldubois** [green-code-initiative/ecoCode#246]
Concatenated strings are automatically optimized by the compiler, in case of a single string or a string appended in a loop. This behaviour is described in the following page :

https://medium.com/javarevisited/java-compiler-optimization-for-string-concatenation-7f5237e5e6ed

Saying that, I think this rule is useless.

**Comment by dedece35** [comment]
As confirmed with core-team, this rule will be deprecated soon because not applicable for Java since jdk8.
