### ISSUE TITLE
[EC2][JAVA] Alert for if statements with instanceof 

### ISSUE THREAD

**Issue by B3ND3L** [green-code-initiative/ecoCode#248]
The rule EC2 include the if statements like : 
`if ( myVar instanceof myClass)`

But the `instanceof` are allowed inside switch only since JAVA17.
That rule is not JAVA11 complient.

Source : https://openjdk.org/jeps/406

Software Versions

    SonarQube Version: Community EditionVersion 9.9 (build 65466)
    Plugin Version: 1.3.0

**Comment by dedece35** [comment]
Hi @B3ND3L,
after analysis and tests, since 1.4.0 (check `CHANGELOG.md` file), this rule was improved a lot.
Since this version `instanceof` operator is ignored.

Maybe check this issue, once 1.4.0 (or above) is installed in your SonarQube.
