### ISSUE TITLE
[EC63] Disable rule for functional interface parameter

### ISSUE THREAD

**Issue by tttooommm56** [green-code-initiative/ecoCode#249]
**Describe the bug**
Ecocode detects unused parameter defined in functional interface.
Sometimes we don't use the parameter but its declaration is mandatory in functional interface.

**Expected behavior**
Ecocode did not detect unused parameter in functional interface.

**Screenshots**
![image](https://github.com/green-code-initiative/ecoCode/assets/36204271/e003d0cf-5f47-45b7-ba0d-d0946a62072c)

**Software Versions**
 - SonarQube Version: Community EditionVersion 9.9 (build 65466)
 - Plugin Version: 1.3.0

**Comment by dedece35** [comment]
Please, wait for draft https://github.com/green-code-initiative/ecoCode/pull/258

**Comment by dedece35** [comment]
hi @tttooommm56,
as https://github.com/green-code-initiative/ecoCode/pull/258 has been merged to deprecate rule EC63, this issue is directly closed.
