### ISSUE TITLE
Release management vs maven packaging (not the same version)

### ISSUE THREAD

**Issue by Silicoman** [green-code-initiative/ecoCode#25]
**Describe the bug**
When I download the latest jar files release from github, it's not the same version printed by sonarqube after loading. 
 - Github = 0.1.1
 - jar file = "0.1.0-SNAPSHOT"

It can make confusion with users.

**Expected behavior**

Versions have to be the same between releases github and the pom version from jar files.

**Screenshots**

![image](https://user-images.githubusercontent.com/11178020/208881016-e03e2514-0539-4672-aed5-60dd08d52c3d.png)

![image](https://user-images.githubusercontent.com/11178020/208881588-9ac90451-c81d-4a2d-b7d9-3ce5800bba32.png)

**Additional context**

Something like `mvn versions:set -DnewVersion=XX.XX` have to be done inside github workflow before releasing.

**Comment by dedece35** [comment]
hi @Silicoman 
please see issue #17 
I'm working on this issue ... to control release system with worklow (github actions) to change version on ´pom.xml' files with ´mvn release:prepare'

**Comment by dedece35** [comment]
Hi @Silicoman,
issue corrected with release 0.2.0 (https://github.com/green-code-initiative/ecoCode/releases)
