### ISSUE TITLE
[EC32] [JAVA] Challenge rule

### ISSUE THREAD

**Issue by diyfr** [green-code-initiative/ecoCode#273]
**EC32** - JAVA

`Initialize builder/buffer with the appropriate size`  
Definition:
*If you know in advance how many characters would be appended, initialize builder/buffer with the appropriate size. They will thus never have to be resized. This saves CPU cycles and therefore consumes less energy.*

In the majority of cases the use of a stringbuiler implies the inability to determine the final size of the produced string.
In addition, a value is defined by default in the StringBuilder source code.

```java
package java.lang;
public final class StringBuilder
    extends AbstractStringBuilder
    implements java.io.Serializable, Comparable<StringBuilder>, CharSequence
{
    /**
     * Constructs a string builder with no characters in it and an
     * initial capacity of 16 characters.
     */
    @IntrinsicCandidate
    public StringBuilder() {
        super(16);
    }
}
```

**Comment by dedece35** [comment]
Hi @diyfr,
thank you for issue.
I agree with you regarding your 2 points but : 
- in a lot of cases, the default value is too small
- StringBuilder will allocate 16 characters by 16 characters very often

I think if you know that 16 characters is very small, we have to initialize StringBuild with a close value to final number of characters to avoid StringBuilder reallocations. This is these reallocations that we want to avoid.
