### ISSUE TITLE
EC69 : Irrelevant rule for Python code

### ISSUE THREAD

**Issue by Paul-Wassermann-CA** [green-code-initiative/ecoCode#276]
Rule EC69 is irrelevant for Python. The rule seems to imply that calling a function in a for statement results in calling this function multiple times, which is not true. 

See the SonarQube screenshot below :

The two following syntaxes are strictly equivalent regarding the number of calls to the `range` builtin function :

```python

for num in range(10):
    pass

iterable = range(10)
for num in iterable:
    pass
```

A simple way to prove see this is using a counter : 

```python 

NUM_CALLS = 0


def func_to_iterable():
    global NUM_CALLS
    NUM_CALLS += 1
    return range(10)


def supposedly_ok_function():
    iterable = func_to_iterable()
    for num in iterable:
        pass


def supposedly_bad_function():
    for num in func_to_iterable():
        pass


if __name__ == '__main__':
    supposedly_bad_function()
    supposedly_ok_function()

    print(NUM_CALLS)
```

This prints `2` since the function is called only twice.

Therefore, I think the rule should be dropped since it's confusing and doesn't make much sense from an eco-design perspective, at least for Python, but it should be investigated for other languages too.

**Comment by dedece35** [comment]
Hello @Paul-Wassermann-CA 
thank you for issue but could you create your issue on the right "ecoCode-python" repository please ? here https://github.com/green-code-initiative/ecoCode-python
and then close this issue.

**Comment by Paul-Wassermann-CA** [comment]
Re-opened in https://github.com/green-code-initiative/ecoCode-python/issues/21
