### ISSUE TITLE
[EC24] java rule not implemented

### ISSUE THREAD

**Issue by Flow35650** [green-code-initiative/ecoCode#308]
**Describe the bug**
In RULES.md, the rule EC24 is noted to be implemented but in fact it is not (only javascript).

**Comment by dedece35** [comment]
Hi @Flow35650,

thank you for issue.
correction done in `RULES.md`.

**Comment by dedece35** [comment]
there is also a previous issue for this pb : please check https://github.com/green-code-initiative/ecoCode/issues/239
