### ISSUE TITLE
[EC2] [Java] Rule "using a switch statement instead of multiple if-else conditions (more than one)" discussion

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode#52]
**Is your feature request related to a problem? Please describe.**
The java rule `using a switch statement instead of multiple if-else conditions (more than one)` with id `cnumr-java:AMIES` isn't really "good" for our society because the argument to change a single `if` statement to a `switch` statement is really not good. Please see followed captures : 

<img width="1194" alt="switch-1" src="https://user-images.githubusercontent.com/12011401/215204410-f115cce3-887f-488e-930d-11fde1b6382e.png">
<img width="1194" alt="switch-2" src="https://user-images.githubusercontent.com/12011401/215204435-7af41038-c609-4cd3-ad09-28b503a49606.png">

**Describe the solution you'd like**
- for the moment, this rule is disabled in our SonarQube
- check why this rule is relevant in our plugin

what is your point of view @glalloue, @jules-delecour-dav, @jhertout, @olegoaer, @mdubois81 ?

**Comment by jhertout** [comment]
Same thing as in issue https://github.com/green-code-initiative/ecoCode/issues/51. I think that for rules like that (that are against common quality rules) we have to be more rigorous or nobody will activate them.

- we must had justifications by tests
- the rule justification text must be more developed than just a reference to the original rule

**Comment by dedece35** [comment]
working on it with issue https://github.com/green-code-initiative/ecoCode/issues/216

**Comment by dedece35** [comment]
optimization done with PR #222
