### ISSUE TITLE
Rename tag to english name

### ISSUE THREAD

**Issue by natixis-caen** [green-code-initiative/ecoCode#55]
The name of the tag is in french "eco-conception".

It might be renamed as "eco-design".

It also seems like I don't have right access to the repository since it has moved. Could you please give me access to create a feature branch then the PR?

**Comment by dedece35** [comment]
Hi @natixis-caen 
you can fork the project, then create a PR from your fork.
Now, we have two repositories : `ecocode` and  `ecocode-mobile`.
Fell free to give us a PR.

please, tell me if you have any problem to do this.

**Comment by dedece35** [comment]
`eco-conception` tag renamed to `eco-design` in python plugin : in progress with PR #77

**Comment by dedece35** [comment]
all is ok now with rules tagging
