### ISSUE TITLE
Error on the plugin ecocode when using Java 1.8 with Sonar Scanner

### ISSUE THREAD

**Issue by fatenhomrani** [green-code-initiative/ecoCode#57]
**Describe the bug**
We use Sonar 8 for multiples Project in our Company.
Since the installation of the plugin ecocode ( version 0.1.1 ) , users get errors on scanning  Legacy projects that run with Java 8 :

**This is the error occured :** 

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project pfx-aggregator: The plugin [ecocodepythonplugin] does not support Java 1.8.0_282: fr/cnumr/python/CustomPythonRulesPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pfx-aggregator

**Comment by dedece35** [comment]
Hi @fatenhomrani ,

to reproduce the problem, can you give me : 
- the exact version of `ecocode` plugin please
- the exact version of SonarQube

As a understand, you launch locally the maven sonar scanner `sonar-maven-plugin` with a JDK 1.8.0_282. Am I right ?

**Comment by fatenhomrani** [comment]
Hi @dedece35 ,
ecocode plugin version : 0.1.1
SonarQube version :  Data Center Edition Version 8.9.10

We Launch Sonar for several projects using CI chain ( Jenkins, Gitlab Runner).

Regarding the diversity of our projects, Sonar Scanner is configured differently and Java version is not similar for all projects.
and exactly, the problem occured when using JDK 1.8.0_282.

0.1.1 is our first installation of the plugin.

Thank you for your help!

**Comment by dedece35** [comment]
Hi @fatenhomrani ,

since the first release 0.1.0, plugin `ecocode` is compiled for jdk 11 (we improved from JDK8 to JDK11 before this first release).
sorry, but we can't go back to JDK 8, several maven dependencies can't go back (like sonar, ...).

our plugins (`ecocode`, `ecocode-mobile`, ...) are all compatible with JDK 11 and 17, but not below, like mentionned on README.md : https://github.com/green-code-initiative/ecoCode#-plugin-java-part-compatibility

**Comment by Silicoman** [comment]
Hi @fatenhomrani,
There is guide about jdk configuration https://community.sonarsource.com/t/java-versions-in-sonarqube/67551
As you are using maven, you can configure toolchains.xml as you must have a settings.xml for your project (inside your git project as wrapper file, or as ConfigFile in Jenkins)

You will need to install jdk11 on your server jenkins if it's not the case.  If jdk11 is declare on global tools from your instance as "jdk11" and your jenkins stage from your pipeline is only a  mvn sonar:sonar, you can encapsulate the shell maven with tool jdk11. 
Or you can add directly as parameter `-Dsonar.java.jdkHome=/usr/lib/jvm/java-11-openjdk-amd64/`

In case, you are running CI with Runner, you will need image container java 11 with a specific steps to run sonar. Or use image sonar scanner directly!

If you need help about Pipeline configuration (jenkins), you will have to share an exemple groovy pipeline (anonymize). There is too many plugins and possibilities to telling you directly the solution.

As your sysadmins/product manager know about Sonarqube enterprise, they will have to upgrade to v9 quickly it's not already done. Your problem with jdk8 will be a global problem but there is a solution as i have discribed. 

Regards

**Comment by dedece35** [comment]
Hi @Silicoman,
top ! thank you for your answer very clear.
We ware waiting for @fatenhomrani tests to check if we could close this issue.

@Silicoman, maybe you can add your answer in a new block in commun documentation ?
thx

**Comment by Silicoman** [comment]
@dedece35 ,
No problem, i will add a chapter troubleshooting.md and a link on readme.md to redirect users.

**Comment by Silicoman** [comment]
My bad, i'm sorry my hypothesis was wrong. I have face many time with java problem to redirect to a generic answer.

After doing differents tests to making documentation and detected something strange.. I have made differents test on the project https://github.com/java8/Java8InAction && https://github.com/hellokaton/java11-examples
I test with differents jdk with parameter sonar.pathHome and SonarQube version  (and i check also sonar maven plugin.)

`mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar -Dsonar.java.jdkHome=/usr/lib/jvm/java-8-openjdk-amd64/ -Dsonar.host.url="http:localhost:9000/sonar" -Dsonar.projectKey=JAVA_8_EXEMPLE -Dsonar.login=xxxxxxx`

| project | Dsonar.java.jdkHome | Sonarqube | ecocode java | Status |
| -------- | ------------------------|--------------|  ------ | ------------|
| java 8    |     jdk 8                        |  v8.9.10 (jdk11)  | 0.1.1   |   KO  | 
| java 8    |    jdk8                          | v8.9.10 (jdk11)   | 0.1.1   | KO    |
| java 8    |    jdk8                          | v9.9.0     (v17)  |  1.+    | OK      |
| java 11  |    jdk 8                         | v8.9.10 (jdk11 )  | 0.1.1   |  KO   |
| java 11  |    jdk11                        | v8.9.10 (jdk11)   | 0.1.1   |  KO   |
| java 11   |    jdk11                        | v9.9.0 (jdk17)  | 1.+      | OK      |
| java 11 |   jdk17                          | v8.9.10 (jdk11) | 0.1.1     | KO    |

i finally conclude the plugin java 0.1.1 released is not compatible with sonarqube v8.9.10 (jdk11).  So if there is a moment where it had ok ,  I will enjoy to know what was the configuration. @fatenhomrani, i'm surprised you only seen the problem on java 8, Have you check other project like java11?

**Comment by dedece35** [comment]
Hi @fatenhomrani 
Do you have some news about your problem ?

A lot of releases have been done since your problem
