### ISSUE TITLE
Add ecoCode plugin to SonarQube Marketplace

### ISSUE THREAD

**Issue by jycr** [green-code-initiative/ecoCode#63]
it would be very useful to add those plugins on the SonarQube Marketplace.

The procedure is relatively straightforward. See: https://github.com/SonarSource/sonar-update-center-properties

If you are OK with this idea, and if you wish, I can do the work for you.

**Comment by ganncamp** [comment]
Out of curiosity, who was that?

**Comment by jycr** [comment]
PR on SonarSource update-center-properties has been created: https://github.com/SonarSource/sonar-update-center-properties/pull/389

**Comment by jycr** [comment]
@dedece35 : Do you have the administration privileges of the [ecoCode project on Sonarcloud](https://sonarcloud.io/project/overview?id=green-code-initiative_ecoCode)?
I think you have to define certain missing parameters to pass the "Quality Gate"

**Comment by dedece35** [comment]
@jycr 
thank you for MR on SonarSource repo.
Yes I have administration rigths on sonarCloud. I've just configured the lack for quality gate computation. thank you for reminding :p (I saw this problem a while ago.
I will push a commit a check it.

**Comment by jycr** [comment]
I will create another PR for mobile plugins because the "non-mobile" plugins project has a security endpoint to fix for SonarCloud Marketplace validation:
https://sonarcloud.io/project/security_hotspots?id=green-code-initiative_ecoCode&sinceLeakPeriod=true

**Comment by jycr** [comment]
@dedece35 : where can I find/download:

* ecocode-android-0.2.x.jar (for SonarQube 9.x compatibility)
* ecodecode-sonar-ios-plugin-0.1.x.jar (for SonarQube 8.x compatibility)
* ecodecode-sonar-ios-plugin-0.2.x.jar (for SonarQube 9.x compatibility)

**Comment by dedece35** [comment]
Hi @jycr, 
for mobile plugins, you can find releases here : https://github.com/green-code-initiative/ecoCode-mobile/releases
there isn't release for ios yet.

there will be the first 1.0.0 release for 2 mobile plugins (android and ios) soon (`ecoCode-mobile`).
the same for standard part (`ecoCode`).

there is no 0.2.0 because is the current version in development.

**Comment by jycr** [comment]
@dedece35 : thanks for this information.
So, I can only create PR for Android plugin.

Is [ecocode-android-0.1.0.jar](https://github.com/green-code-initiative/ecoCode-mobile/releases/download/0.1.0/ecocode-android-0.1.0.jar) compatible with latest version of SonarQube (from 8.9.+ to 9.9 included) ?

**Comment by dedece35** [comment]
@jycr yes as mentionned here : https://github.com/green-code-initiative/ecocode-mobile

**Comment by jycr** [comment]
As mentioned here : https://github.com/green-code-initiative/ecocode-mobile , v0.1.0 not compatible from 8.9 to 9.3

**Comment by jycr** [comment]
PR on SonarCloud marketplace for ecoCode-android 0.1.0 (for SonarQube 9.4+): https://github.com/SonarSource/sonar-update-center-properties/pull/390

**Comment by jules-delecour-dav** [comment]
> Out of curiosity, who was that?
> 
> Because I don't remember saying that and I'm the one who typically vets new plugins

To clarify, we wanted to impletement index on the Sonarqube Dashboard in order to add "Green bugs" next to "Bugs and vulnerability. What we understood was our plugin needed to be embedded in the "core" code of Sonarqube to access to this  dashboard. Last year we met Sonarsource team and they recommended us to prouve that "Green rules" were relevant with tests and measurements (we started this work few month ago and you can see on some rules oh PHP, the result). 

Not sure that was directly linked to Sonarqube Marketplace. It could be very interesting to integrate the plugin to your Marketplace if it checks all your requierements

**Comment by ganncamp** [comment]
Thanks for that detail. It makes more sense now. 
While you can add extra pages under a 'More' menu (it shows up once there are pages that go under it) you can't modify what shows up on the homepage.

**Comment by jycr** [comment]
PR for mobile plugins has been merge with https://github.com/SonarSource/sonar-update-center-properties/pull/389

@dedece35 : do you know when iOS plugin will be released?

**Comment by ganncamp** [comment]
I assume this is just rules? So I just need a project appropriate for each language (or one to rule them all?) so I can take a look at some representative issues. To be clear, I don't need to see every rule in action. I just need to get an idea of how it works / looks

**Comment by olegoaer** [comment]
> I assume this is just rules? So I just need a project appropriate for each language (or one to rule them all?) so I can take a look at some representative issues. To be clear, I don't need to see every rule in action. I just need to get an idea of how it works / looks

Hello. For _ecoCode Mobile_, the complete list of rules to implement in the plugin is here: https://github.com/cnumr/best-practices-mobile

**Comment by ganncamp** [comment]
I'll see the rules once I load up the plugins in a test instance. I need to _run_ the rules against some sample projects.

**Comment by olegoaer** [comment]
> 

For sake of simplicity, you can access our public/demo running instance here : https://sonarqube.ecocode.io/

Click on _More Options_. Then :
- login: summer-school
- password: Hf6kt

Browse the Android project name [webinar_demo](https://sonarqube.ecocode.io/dashboard?id=webinar_demo)

**Comment by ganncamp** [comment]
I need to run this myself. Can you point me to those projects to I can clone & analyze them? Also, I'll need to run analysis for each plugin.

**Comment by olegoaer** [comment]
> I need to run this myself. Can you point me to those projects to I can clone & analyze them? Also, I'll need to run analysis for each plugin.

You can analyse these two Android apps:
1. https://git.univ-pau.fr/summer-school/QuelPrixImmo.git
2. https://git.univ-pau.fr/summer-school/uppamaps.git

**Comment by dedece35** [comment]
Hi @ganncamp,
I confirm that there are one plugin for each language (java, php, python, javascript, android and iOS).

We are currently creating test project to run sample like you want and for new people who wants to test plugins : 
- java plugin
   - install notes : https://github.com/green-code-initiative/ecoCode/blob/main/INSTALL.md
   - test project issue (I'm working on it) : #65 
      - purpose : create a test project from unit test existing in plugin code
- php, python, javascript : no test project existing now, but once ok for java plugin, the others test project will follow
- iOS plugin
   - install notes : https://github.com/green-code-initiative/ecoCode-mobile/blob/main/INSTALL.md
   - test project : https://github.com/green-code-initiative/ecoCode-mobile-ios-swift-test-project
- android plugin
   - install notes : same of iOS
   - test project : not existing for now

**Comment by dedece35** [comment]
Hi @ganncamp, @jycr 
the new repository https://github.com/green-code-initiative/ecoCode-java-test-project contains the project test for Java language to check Java plugin.
Please read the README.md of this new repository to understand how to test.

The same way is coming for the others languages (PHP, python).

Please, feel free to ask me question if not clear (to improve documentation if needed).

**Comment by jycr** [comment]
@ganncamp shared some very interesting feedbacks with this reply: https://community.sonarsource.com/t/new-plugin-ecocode-requesting-inclusion-in-sonarqube-marketplace/85398/4

@dedece35: Do you need me to create an issue for each feedback point in the corresponding green-code-initiative Git repo?

**Comment by dedece35** [comment]
Hi @jycr,
indeed, very intersting feedback, you're right.
thanks a lot @ganncamp !!!

My point of view is to put all feedbacks only in this current issue because it deals with SonarQube Marketplace integration. By this way, only one commiter will make all modifications regarding the current issue and thus, all feedbacks.

Another solution would be to create one issue for each feedback, and follow all issues in this current issue ... with a link between issues or a tag to identify them. Why not ?!
@jhertout : your point of view ?

@jycr, would you help us and contriuting with PRs with few code modifications ? :p 
(thank you for your issue here and on sonarsource.com)

**Comment by jhertout** [comment]
Hi @dedece35 ,

I think we need to synthesize somewhere the remaining things to do because it is complicated to follow in this thread. I was a little lost while reading. In an other issue or in this issue I don't know. Maybe an other that contains only the technical things to do and we keep this one to discuss the subject and don't pollute the technical one?

**Comment by dedece35** [comment]
Hi @jhertout @jycr 
I'm ok with @jhertout.

**Comment by jycr** [comment]
I was finally able to fix majority of issues raised in PR #79 (as you see in linked commits above).
I still have to do the same for Android and iOS plugins in their respective git repo

**Comment by dedece35** [comment]
Hi @jycr 
I've just checked and merged PR #79.
Would you like to add other modifications for Sonarqube Marketplace requirements in this issue or create another issue / PR for them ?

**Comment by jycr** [comment]
There are other possible improvements/corrections, but those which were essential were normally included in the PR which you merged.

As soon as a release of these plugins will be made, I will make a new submittion attempt to the SonarSource Marketplace.

**Comment by dedece35** [comment]
Hi @jycr,

yes no problem to discuss about it (french preferred for me :p ).
when are you available ? (today, tomorrow, monday and tuaesday ?) please give me some available slots to choose.

another question about your modifications for SonarQube marketPlace.
You changed ids of rules. no problem. but I see that there are some ids duplicated between php, python and java plugins ?
please, check here : 
- https://github.com/green-code-initiative/ecoCode/tree/main/java-plugin/src/main/resources/fr/greencodeinitiative/l10n/java/rules/java
- https://github.com/green-code-initiative/ecoCode/tree/main/php-plugin/src/main/resources/fr/greencodeinitiative/l10n/php/rules/custom
- https://github.com/green-code-initiative/ecoCode/tree/main/python-plugin/src/main/resources/fr/greencodeinitiative/l10n/python/rules/python
is it right for SonarQube ?
example : 
- java VS python : EC4, EC69, EC72, EC74
- java VS php : EC4, EC67, EC69, EC72, EC74
- python VS php : EC4, EC34, EC69, EC72, EC74

ths.

**Comment by dedece35** [comment]
@jycr, for "conflicts" on rule keys ... no problem, after checking and reflexion I undertsand : the same key for the same rule in different languages.
I'm OK.

**Comment by glalloue** [comment]
thanks @jycr all clear !

**Comment by dedece35** [comment]
Hi @jycr,
release 1.1.0 done : https://github.com/green-code-initiative/ecoCode/releases/tag/1.1.0 

you can play with it :p

**Comment by jycr** [comment]
The ecoCode plugins for Java, PHP and Python have been published on the [SonarSource Marketplace](https://docs.sonarqube.org/9.9/instance-administration/plugin-version-matrix/).

I suggest closing this ticket.

For other plugins, I think it's best to create a specific ticket for each one.
