### ISSUE TITLE
Create a test project to check new plugin rule in real environment

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode#65]
**Is your feature request related to a problem? Please describe.**
currently, when a developer create a new rule in the plugin, he can test it with unit tests but not on a real SonarQube environment.

**Describe the solution you'd like**
Create a new project / repository containing an example application (one by language ?) which can be used to push on local development SonarQube environment to check if the new rule is OK.
It would be an integration test.
Maybe we can use all current source files used in unit tests.

**Comment by dedece35** [comment]
Hi @jhertout,
I've just added a new test-project for java-plugin : here is the commit.
I added all Java files found in src/test/files for unit tests of java-plugin.
What do you think about it ?

**Comment by jhertout** [comment]
Hi @dedece35,

It the same for us, our test projects is almost like the unit tests. The only thing is that we add a comment at the end of a line that should trigger an issue like this : 

`params.screenBrightness = BRIGHTNESS_OVERRIDE_FULL; // Issue {Sobriety: Brightness Override}`

This enable us to know if the rule is triggered on the good line without thinking and if it it is the rule we expect.
It is a good way to easily know if a rule triggers on a bad line too (a line without comment).

**Comment by dedece35** [comment]
Hi @jhertout,
indeed, good idea !
maybe plan a technical point to show me how this system works.

**Comment by utarwyn** [comment]
Hello, do you think we should put the test projects in another repository? It's just an idea in order not to overload this repository, maybe a bad one. It depends if we need them during the development phase or not.

**Comment by dedece35** [comment]
The new repository is ready for Java language : https://github.com/green-code-initiative/ecoCode-java-test-project
are you ok @jhertout @utarwyn ?
if yes, I will create an issue for each other langugage to do the same (php, python)

**Comment by dedece35** [comment]
for python plugin, I created the new repo https://github.com/green-code-initiative/ecoCode-python-test-project
It help me to correct #64 
you can review it if you want. I took into account the @jhertout 's review note above on java plugin

**Comment by jhertout** [comment]
Hi @dedece35,
I looked the Python test project and it seems ok to me. We are working on some Python rules, so we will quickly have to work on it. We will see if all is ok!

**Comment by dedece35** [comment]
Hi, all test projects are up and ok.
