### ISSUE TITLE
Check if possible to make plugin 1.8 jdk compatible

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode#66]
**Is your feature request related to a problem? Please describe.**
Currently, plugin requires a 11 JDK at minimum. But, many societies still uses a 1.8 JDK.
check #57 

**Describe the solution you'd like**
Check if possible to make plugin 1.8 JDK compatible with a minimum code modifications.

**Comment by Silicoman** [comment]
Hi, 
There is some misinformations about usage of jdk inside pipeline CI. 
There is a [guide java-versions-in-sonarqube](https://community.sonarsource.com/t/java-versions-in-sonarqube/67551) explaining this.
When you are using a scanner, you have to execute under compatible java version. You can have a CI with jdk8 as global and when it's time to run sonarscanner (or plugin maven), you switch to jdk11/17.  I have in mind **toolchains.xml** from maven is here to solve this problem at global (may need confirmation).
You can add this sonar property in *sonar.properties* or as cli parameter :
`-Dsonar.java.jdkHome= /usr/lib/jvm/java-11-openjdk-amd64/`

To conclude, SonarQube LTS is now v9.9 . Projects have to move to Sonarqube v9+ to security concerns (and new features!). Java 8 projects will continue to be scannable with this previous trick under Sonarqube v9+. Only redirection doc have to be done to users.

**Comment by dedece35** [comment]
I close this issue becasue of dupication of #57
