### ISSUE TITLE
Fix Security Hotspot

### ISSUE THREAD

**Issue by jycr** [green-code-initiative/ecoCode#69]
In order for the request for publication of the plugin on the SonarSource Marketplace (see: https://github.com/green-code-initiative/ecoCode/issues/63) to be validated, the "Quality Gate" must be "passed". 
The latest analysis shows that a "Security Hotspot" must be fix:

https://sonarcloud.io/project/security_hotspots?id=green-code-initiative_ecoCode&sinceLeakPeriod=true

**Comment by dedece35** [comment]
all security hotspots corrected and more (optimization of Pattern usage for performance and security)
see https://github.com/green-code-initiative/ecoCode/commit/5ed1076296f13212f4ce52ffd6dec5907209d4e6
(and previous)
