### ISSUE TITLE
After an PHP analysis, no ecocode code smells appears in my Sonar project.

### ISSUE THREAD

**Issue by guiyom19** [green-code-initiative/ecoCode#71]
First of all, thank you for your work!

After an analysis, no ecocode code smells appears in my Sonar project :

I added the ecocode-php-plugin-0.2.2.jar in the extensions/plugins directory.
All rules appears in my quality profiles and I've activate them.
 
![image](https://user-images.githubusercontent.com/28901004/223451738-285a5ab6-2b4e-4813-ba56-33c58a441870.png)

My project use the good quality PHP ecoCode profile where I use those rules.

But when I add some dirty code on my Symfony project ie : 
![image](https://user-images.githubusercontent.com/28901004/223452204-62ee6d13-bc5e-48fa-9bb7-d986526bfd2d.png)
Only basic sonar way code smell is detected.

Do I missed something in my Sonar configuration?

Thanks a lot for your answer

**Software Versions**
 - SonarQube Version: 9.4
 - Plugin Version: 0.2.2

Guillaume

**Comment by dedece35** [comment]
Hi @guiyom19,

thank you for your issue.

The best thing to do to check this issue is to create a test project like mentionned here #65 (in progress for java language).
I will work on it soon unless if you want to create it ;p

**Comment by dedece35** [comment]
I think is the same problem as #64 for python plugin (correction with PR #77)
I will work on it soon.

**Comment by dedece35** [comment]
for information : 
- PR in review internally : #82 
- a new PHP test-porject to verify plugin in real environment : https://github.com/green-code-initiative/ecoCode-php-test-project

**Comment by dedece35** [comment]
Hi @guiyom19,
all is ok now.
please, test it with out new real test project above.

**Comment by guiyom19** [comment]
Hi @dedece35,
I finally got it work with your new 1.0.0 php plugin.  
Many ecocode issues pop as bugs in my projects
![image](https://user-images.githubusercontent.com/28901004/227944082-6b64b170-3d57-4acf-b53b-c7f8171c25bb.png)
Many thanks again and good luck for the next steps!
