### ISSUE TITLE
Move max maven requirement to 3.9.0 version

### ISSUE THREAD

**Issue by glalloue** [green-code-initiative/ecoCode#74]
The ./check_requirement.sh script return error when 3.9.0 version from maven is installed.
Max version installed is supposed to be 3.8.7

3.9.0 version has been released January 31 this year.
So many developers can use this version and maybe they already installed it before next hackaton event.

- Check all repository using maven to validate 3.9.0 version compatibility
- modify check requirement scripts to accept 3.9.0 as max maven version

**Comment by dedece35** [comment]
Hi @glalloue,
- [ OK ] check maven 3.9.0 for `ecoCode`
- [ OK ] check maven 3.9.0 for `ecoCode-mobile`
- [ OK ] upgrade `eco-common` tools
