### ISSUE TITLE
SonarQube plugins homepage link is broken

### ISSUE THREAD

**Issue by glalloue** [green-code-initiative/ecoCode#76]
When i install plugins on sonarqube instance, homage link is broken :

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/10628710/225033480-34230c61-9062-4365-bd05-bbbe3ac7c28b.png">

** How to reproduce**
1. Go to administration menu
2. Click on marketplace tab
3. Scroll down to plugins section
4. Select "installed" tab
5. Click on "homepage" link

<img width="889" alt="image" src="https://user-images.githubusercontent.com/10628710/225034106-1fea8d07-8d3f-4846-8e66-205eb9a49240.png">

**Expected behavior**
Link to the good folder associated to the selected plugin.

**Screenshots**
see above

**Software Versions**
 - SonarQube Version: 9.9
 - Plugin Version: 0.3.0-snapshot

**Additional context**
- problem also concern php / java / python plugins

**Comment by dedece35** [comment]
correction done
