### ISSUE TITLE
Rework documentation pages about implemented rules

### ISSUE THREAD

**Issue by jycr** [green-code-initiative/ecoCode#86]
Pages concerned:

* docs/rules/web-matrix.md
* docs/rules/web-rules.md

Needs:
* Add the _rule key_ on each line that the described rule is implemented

**Comment by dedece35** [comment]
PR #88 in progress : waiting for review (@glalloue)

**Comment by jycr** [comment]
SonarQuabe has a centralized repository to describe each of its rules, which is independent of the different existing implementations:
https://github.com/SonarSource/rspec

This makes it possible to have a centralized vision of the rules, and their declension according to the programming languages.
This also helps to avoid problems/conflicts in assigning identifiers (keys) for the rules.

This also makes it easier to write descriptions (in asciidoc/markdown).

Perhaps this orientation could become interesting for the ecoCode rules?

**Comment by dedece35** [comment]
hi @jycr 
good idea ... maybe to discuss about it in our Slack or during a weekly live meeting to expose more accurately your idea.

**Comment by utarwyn** [comment]
Hello! I think it's a very good idea to centralize the rules, to have one common knowledge base for the ecoCode project. It will simplify even more the readability of the rules, especially for those that are implemented, to be implemented, etc. :100:

However, I don't think we should copy their structure as it exists in their repository. When reading their README you can see that they have created a lot of processes to maintain the rules, and rightly so. But we don't have the same project size, the goal is not to make the process unnecessarily complex for the community.

**Comment by jhertout** [comment]
Hi @jycr , I think it is a good idea too. We tried to do something for eco-mobile but it is not in the sate of https://github.com/SonarSource/rspec. I thing we should discuss how it works and how we can apply this to our project.

**Comment by glalloue** [comment]
concerning the original subject to rework those pages : 

- docs/rules/web-matrix.md
- docs/rules/web-rules.md

Work is done by this PR : https://github.com/green-code-initiative/ecoCode/pull/88

rule key on each line is added when it was possible.

Maybe we can create a new issue related to rules centralized repository and close this one.
What is your opinion @dedece35 ?

**Comment by dedece35** [comment]
correction done with PR #88
